# Site settings
title: Music and the Middlebrow
description: An interdisciplinary project bringing together scholars working on musical culture and the middlebrow.
baseurl: ""
defaults:
  - values:
      parent: /
markdown: kramdown
